#!/usr/bin/env python3
'Execute shell commands and emulate inputs based on libinput events'
# Maxime Wack 2026

import os
import sys
import argparse
import subprocess
import shlex
import re
import getpass
import fcntl
import platform
import math
import signal
from pathlib import Path
from packaging.version import Version

PROGPATH = Path(sys.argv[0])
PROGNAME = PROGPATH.stem

# Conf file containing gesture commands.
# Search first for user file then system file.
CONFNAME = f'{PROGNAME}.conf'
USERDIR = os.getenv('XDG_CONFIG_HOME', os.path.expanduser('~/.config'))
CONFDIRS = (USERDIR, '/etc')

class OPTIONS:
    'Singleton class for storing options'

    # Configurable options with their default values and validation functions
    available = dict(
        swipe_min_threshold   = dict(default = 5    , valid = float, help = "Minimum travel distance to register a swipe"),
        ratio_min_threshold   = dict(default = .2   , valid = float, help = "Minimum ratio to register a pinch"),
        angle_min_threshold   = dict(default = 10   , valid = float, help = "Minimum angle to register a rotation"),
        hold_min_threshold    = dict(default = .5   , valid = float, help = "Minimum time (in s) to register a hold"),
        swipe_chain_threshold = dict(default = 100  , valid = float, help = "Minimum travel distance to register a chained swipe"),
        ratio_chain_threshold = dict(default = .4   , valid = float, help = "Minimum ratio to register a chained pinch"),
        angle_chain_threshold = dict(default = 100  , valid = float, help = "Minimum angle to register a chained rotation"),
        update_timer          = dict(default = .1   , valid = float, help = "Time interval at which update a continuous motion"),
        device                = dict(default = "all", valid = str,   help = '"all", or device name, or device path'))

    def __init__(self):
        'Create attributes from the dict and set default values'
        for opt, params in self.available.items():
            setattr(self, opt, params["default"])

    def set(self, option, value):
        'Set an option value (arg > conf > default)'
        arg = getattr(args, option)
        valid = self.available[option]["valid"]

        if arg:
            try:
                setattr(self, option, valid(arg))
            except:
                print(f'Option {option} must be of type {valid.__name__}. Falling back on default')
        else:
            try:
                setattr(self, option, valid(value))
            except:
                return f'Option {option} must be of type {valid.__name__}'

    instance = None

    def __new__(cls):
        'Ensure single instance'
        if cls.instance is None:
            cls.instance = super().__new__(cls)
            return cls.instance

# Create the singleton options object
options = OPTIONS()

class ACTIONS:
    'Singleton class for storing actions'

    # Configurable actions and how to parse them
    available = dict(switch = {'toggle'   : ('tablet-mode', 'lid', 'keypad-slide'),
                               'state'    : ('on', 'off'),
                               'command'  : '.*'},
                     swipe =  {'motion'   : ('up', 'down', 'left', 'right'),
                               'fingers' : r'\d',
                               'modifier?': ('pre', 'chain', 'continuous', 'end', 'post'),
                               'command'  : r'[^\[\]]+',
                               'wclass?'   : r'\[.*\]'},
                     pinch =  {'motion'   : ('in', 'out'),
                               'fingers' : r'\d',
                               'modifier?': ('pre', 'chain', 'continuous', 'end', 'post'),
                               'command'  : r'[^\[\]]+',
                               'wclass?'   : r'\[.*\]'},
                     rotate = {'motion'   : ('cw', 'ccw'),
                               'fingers' : r'\d',
                               'modifier?': ('pre', 'chain', 'continuous', 'end', 'post'),
                               'command'  : r'[^\[\]]+',
                               'wclass?'   : r'\[.*\]'},
                     hold =   {'fingers' : r'\d',
                               'modifier?': ('pre', 'end'),
                               'command'  : r'[^\[\]]+',
                               'wclass?'   : r'\[.*\]'})

    conf_re = {}
    actions = {}
    parsed_actions = []

    def __init__(self):
        'Build parsing regexes from dict'
        for action, params in self.available.items():
            verbs = []
            for verb, arg in params.items():
                arg = '|'.join(arg) if type(arg).__name__ != "str" else arg
                if verb[-1] == "?":
                    verbs.append(rf"""(?P<{verb[:-1]}>{arg})?""")
                else:
                    verbs.append(rf"""(?P<{verb}>{arg})""")
            self.conf_re[action] = re.compile(rf"""\s*""".join(verbs))

    def parse(self, restrict, action, args):
        'Parse a conf line with the action regexes'
        fields = self.conf_re[action].match(args)

        if not fields:
            return f'Could not parse {action} line'

        fields = fields.groupdict()

        if action == 'switch':
            self.add_switch(**fields)
        else:
            self.add(restrict, action, **fields)

    def add_switch(self, toggle, state, command):
        'Add a switch action'
        self.parsed_actions.append(f'switch {toggle:12} {state:3} {command}')
        self.build_path('switch', toggle, state, command = command)

    def add(self, restrict, action, fingers, wclass, modifier, command, motion = None):
        'Add all other actions'
        fingers = int(fingers)
        modifier = modifier or 'end'

        self.parsed_actions.append(f'{restrict or '':7} {action:6} {fingers} {motion:5} {modifier:10} {command:60} {wclass or '':>}')

        wclass = wclass and wclass[1:-1]
        restrict = [restrict] if restrict else ['touch', 'gesture']

        for r in restrict:
            self.build_path(r, fingers, action, motion, wclass, modifier, command = command)

            if not self.actions[r][fingers][action].get('apps'):
                self.actions[r][fingers][action]['apps'] = set()

            self.actions[r][fingers][action]['apps'].add(wclass)

    def build_path(self, *args, command):
        'Construct the actions dict object up to the given path'
        current = self.actions

        for arg in args[:-1]:
            if not current.get(arg):
                current[arg] = {}
            current = current[arg]

        current[args[-1]] = command

    def validate_path(self, path):
        'Return the first path item not matching, or the resulting action path'
        current = self.actions
        for item in path:
           current = current.get(item)
           if not current:
               return (False, item)

        return (True, current)

    def __str__(self):
        return '\n'.join(sorted(self.parsed_actions))

    instance = None

    def __new__(cls):
        'Ensure single instance'
        if cls.instance is None:
            cls.instance = super().__new__(cls)
            return cls.instance

actions = ACTIONS()

args = None

def open_lock(*args):
    'Create a lock based on given list of arguments'
    # We use exclusive assess to a file for this
    fp = Path('/tmp', '-'.join(args) + '.lock').open('w')

    try:
        fcntl.lockf(fp, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except IOError:
        return None

    return fp

def run(cmd):
    'Run command'
    try:
        subprocess.Popen(cmd)
    except Exception as e:
        print(str(e), file = sys.stderr)

def listen_libinput():
    'Run libinput debug-events and listen to its output'
    # Make sure only one instance running for current user
    user = getpass.getuser()
    proglock = open_lock(PROGNAME, user)
    if not proglock:
        sys.exit(f'{PROGNAME} is already running for {user}, terminating ..')

    # User needs to belong to the input group to access the device
    # "sudo gpasswd -a $USER input" then log out/in
    command = f'stdbuf -oL -- libinput debug-events'

    cmd = subprocess.Popen(shlex.split(command),
                           stdout = subprocess.PIPE,
                           bufsize = 1,
                           universal_newlines = True)

    # Avoid producing zombie processes
    signal.signal(signal.SIGCHLD, signal.SIG_IGN)

    return cmd

def get_options():
    'Parse the command-line options'
    global args
    opt = argparse.ArgumentParser(description = __doc__)
    opt.add_argument('-c',
                     '--conffile',
                     help = 'alternative configuration file')
    opt.add_argument('-v',
                     '--verbose',
                     action = 'store_true',
                     help = 'output diagnostic messages')
    opt.add_argument('-d',
                     '--debug',
                     action = 'store_true',
                     help = 'output diagnostic messages only, do not action gestures')
    opt.add_argument('-r',
                     '--raw',
                     action = 'store_true',
                     help = 'output raw libinput output')
    for option, params in options.available.items():
        opt.add_argument('--' + option,
                         help = params["help"])
    args = opt.parse_args()

    if args.debug:
        args.verbose = True

def unexpanduser(cfile):
    'Return absolute path name, with $HOME replaced by ~'
    relslash = Path(os.path.abspath(str(cfile)))

    try:
        relhome = relslash.relative_to(os.getenv('HOME'))
    except (ValueError, TypeError):
        relhome = None

    return ('~/' + str(relhome)) if relhome else str(relslash)

def read_conf(conffile, defname):
    'Search for configuration file. Use file given as command line argument, else look for file in search dir order'
    if conffile:
        confpath = Path(conffile)

        if not confpath.exists():
            sys.exit(f'Conf file "{conffile}" does not exist.')
    else:
        for confdir in CONFDIRS:
            confpath = Path(confdir, defname)

            if confpath.exists():
                break
            else:
                sys.exit('No file {defname} in {" or ".join([unexpanduser(Path(c)) for c in CONFDIRS])}.')

    # Hide any personal user dir/names from diag output
    confname = unexpanduser(confpath)

    # Read and process the conf file
    get_conf(confpath, confname)

    # List out available gestures and configured options if that is asked for
    if args.verbose:
        if actions.actions:
            print('', f'Gestures configured in {confname}:', sep = '\n')
            print(actions)

        print('', 'OPTIONS:', sep = '\n')
        for option, params in options.available.items():
            value = getattr(options, option)
            default = params["default"]
            if value != default:
                print(f'{option:24} {value:>5} ({default=})')
            else:
                print(f'{option:24} {value:>5}')

        print()

def get_conf(conffile, confname):
    'Read given configuration file and store internal actions etc'
    conf_comment_re = re.compile(r"""
        ^\# |                                  # Line starts with a comment
        ^\[[^\[\]]+\]\s*                       # Line is a section header
    """, flags = re.VERBOSE)

    with conffile.open() as fp:
        for num, line in enumerate(fp, 1):
            line = line.strip()

            if not line or conf_comment_re.match(line):
                continue

            errmsg = get_conf_line(line)

            if errmsg:
                sys.exit(f'Error at line {num} in file {confname}:\n>> {line} <<\n{errmsg}.')

def get_conf_line(line):
    'Process a single line in conf file'
    key, *argslist = line.split(maxsplit = 1)

    restrict = None

    if key == 'touch' or key == 'gesture':
        restrict = key
        key, *argslist = argslist[0].split(maxsplit = 1)

    if key in list(options.available):
        return options.set(key, argslist[0])
    elif key in list(actions.available):
        return actions.parse(restrict, key, argslist[0])

def center(points):
    center = [0, 0]

    for point in points:
        center[0] += point[0]
        center[1] += point[1]

    return (center[0] / len(points), center[1] / len(points))

def diff(point1, point2):
    return((point2[0] - point1[0], point2[1] - point1[1]))

def mean_dist(points, center):
    dist = 0

    for point in points:
        vec = diff(center, point)
        dist += math.sqrt(vec[0]**2 + vec[1]**2)

    return dist / len(points)

def norm_cross_prod(x1, y1, x2, y2):
    return (x1*y2 - x2*y1) / (0.0000001 + math.sqrt(x1**2 + y1**2) * math.sqrt(x2**2 + y2**2))

def calc_angle(startPos, lastPos, startCenter, lastCenter):
    angle = 0
    xc1, yc1 = startCenter
    xc2, yc2 = lastCenter

    for i in range(0, len(startPos)):
        x1, y1 = startPos[i]
        x2, y2 = lastPos[i]
        angle += math.asin(norm_cross_prod(x1 - xc1, y1 - yc1, x2 - xc2, y2 - yc2))

    return angle / len(startPos)

def touch_gesture(startPos, lastPos):
    startCenter = center(startPos)
    lastCenter = center(lastPos)

    xrel, yrel = diff(startCenter, lastCenter)
    dist = math.sqrt(xrel**2 + yrel**2)

    if len(lastPos) > 1:
        ratio = mean_dist(lastPos, lastCenter) / mean_dist(startPos, startCenter)
        angle = calc_angle(startPos, lastPos, startCenter, lastCenter) / math.pi * 180
    else:
        ratio = 1
        angle = 0

    if abs(angle) > options.angle_min_threshold:
        return({'gesture': 'PINCH',
                'params': [0, 0, 0, 0, ratio, angle]})
    elif abs(math.log(ratio)) > options.ratio_min_threshold:
        return({'gesture': 'PINCH',
                'params': [0, 0, 0, 0, ratio, angle]})
    else:
        return({'gesture': 'SWIPE',
                'params': [0, 0, xrel, yrel]})

# Parsing regexes for libinput events
params_re = dict(
    LIBINPUT = re.compile(r"""
        .*?
        (?P<device> event\d+)                  # Device
        \s*
        (?P<event> [A-Z_]+)                    # Event
        \s*
        (?:\d+)?                               # Event number within frame
        \s*
        (\+ (?P<time> \d+\.\d+) s)?            # Time
        \s*
        (?P<params> .*)?                       # Params
    """, flags = re.VERBOSE),

    DEVICE = re.compile(r"""
        (?P<name>.*?)
        \s*
        (?P<seat>seat\d \s default)
        \s*
        (?P<group>group\d+)
        \s*
        (cap:(?P<capabilities>[kpgStT]+))
        \s*
        (size \s (?P<sizex>\d+) x (?P<sizey>\d+) mm)?
    """, flags = re.VERBOSE),

    SWITCH = re.compile(r"""
        switch
        \s+
        (?P<switch> tablet-mode | lid | keypad-slide) # Switch name
        \s*
        state \s+ (?P<state> 0 | 1)                   # State
    """, flags = re.VERBOSE),

    TOUCH = re.compile(r"""
        (?P<finger> \d)?                          # Finger
        \s*
        \( (?P=finger) \)?
        \s*
        ((?P<x> \d+\.\d+) /\s* (?P<y> \d+\.\d+))? # Absolute position 0-100% of width/height
    """, flags = re.VERBOSE),

    GESTURE = re.compile(r"""
        (?P<fingers> \d)                                                                    # Fingers
        \s*
        (?P<cancelled>cancelled)?
        \s*
        ((?P<x> -? \d+\.\d+) \s* / \s* (?P<y> -? \d+\.\d+))?                                # Absolute position 0-100% of width/height
        \s*
        ( \( \s* (?P<x2> -? \d+\.\d+) \s* / \s* (?P<y2> -? \d+\.\d+) \s* unaccelerated\) )? # Absolute position 0-100% of width/height
        \s*
        ((?P<ratio> \d+\.\d+) \s* @ \s* (?P<angle> -? \d+\.\d+))?
    """, flags = re.VERBOSE),

    POINTER = re.compile(r"""
        ((?P<x> -? \d+\.\d+) \s* / \s* (?P<y> -? \d+\.\d+))?
        (BTN_(?P<button> LEFT | MIDDLE | RIGHT) \s \( \d+ \) \s (?P<state> pressed | released))?
        (vert \s ((?P<vert> -?\d+\.\d+) / 0\.0 \*?) \s horiz \s ((?P<horiz> -?\d+\.\d+) / 0\.0 \*?))?
    """, flags = re.VERBOSE))

class HANDLER:
    'Class for device handler objects'

    # Available capabilities
    cap_dict = dict(k = "keyboard",
                    T = "tablet",
                    t = "touch", # in actions
                    p = "pointer", # match to gesture too ? or disregard because we don't want simple pointers ?
                    g = "gesture", # in actions
                    S = "switch") # in actions

    def __init__(self, device):
        'Initialize a device handler'
        self.device = device
        self.LISTENERS = dict(DEVICE  = self.listener_device,
                              TOUCH   = self.listener_touch,
                              GESTURE = self.listener_gesture,
                              SWITCH  = self.listener_switch,
                              POINTER = self.listener_pointer)
        self.enabled = True

    def add(self, name, capabilities, sizex, sizey):
        'Populate handler parameters and decide if it\'s enabled'
        self.name = name
        self.capabilities = {v for k, v in self.cap_dict.items() if k in list(capabilities)}
        self.size = (sizex, sizey)

        self.release()

        # If no action relevant, disable handler
        self.enabled = True if {k:v for k, v in actions.actions.items() if k in self.capabilities} else False

        return {'verbose': f'{'Adding  ' if self.enabled else 'Ignoring'} device {name:50} ({self.device}) {self.capabilities}'}

    def remove(self):
        'Remove the handler for an unplugged device'
        del(handler[self.device])
        return {'verbose': f'Removing device  {self.name:50} ({self.device})'}

    def grab(self, device_type, time = None):
        'Grab a handler and set its current device type, the focused window class, and the starting time'
        self.busy = True

        self.wclass = subprocess.run(['xdotool', 'getwindowfocus', 'getwindowclassname'], capture_output = True).stdout.decode('utf-8').strip()
        self.start_time = time
        self.path = [device_type]

    def release(self, message = None):
        'Release a handler and reset its state'
        self.busy = False
        self.holding = False
        self.chaining = False
        self.pre = False

        self.data = dict(x = 0, y = 0, dx = 0, dy = 0, ratio = 0, dratio = 0, angle = 0, dangle = 0)

        self.path = []
        self.start_time = None
        self.gesture = None
        self.motion = None
        self.wclass = None
        self.available_motions = None
        self.available_actions = None

        return {'verbose': message} if message else None

    def extend_path(self, *items):
        'Extend the action path and validate it'
        self.path.extend(items)
        return actions.validate_path(self.path)

    def run(self, command = None, *items):
        'Run the given command or the one at the end of path + *items'
        if not command:
            valid, res = self.extend_path(*items)
            if not valid:
                return self.release(f'No path to action from {res} in {self.path}. Releasing handler')
            else:
                command = res

        # Replace {} in commands
        data = {k: int(v) for k, v in self.data.items()}
        exprs = re.findall(r'\{[^\{\}]+\}', command)
        for expr in exprs:
            command = command.replace(expr, str(eval(expr[1:-1], {}, data)))

        if args.verbose:
            print(f'{self.path} {data}')
            print('  ', command)
            print('')

        if not args.debug:
            run(shlex.split(command))

        return None

    def switch(self, switch, state):
        'Handle a switch action'
        if self.busy:
            return {'debug': f'Handler for device {self.device} is in use (shouldn\'t be possible!)'}

        self.grab('switch')

        res = self.run(switch, state)

        return res if res else self.release()

    def hold(self, device_type, event, time, fingers, cancelled):
        'Handle a hold action'
        if event == 'BEGIN':
            if self.busy:
                return self.release(f'Handler for device {self.device} is in use (shouldn\'t be possible!)')

            self.grab(device_type, time)
            valid, res = self.extend_path(fingers, 'hold')

            if not valid:
                return self.release(f'No path to action from {res} in {self.path}. Releasing handler')
            else:
                # use a realtime timer to run 'pre' action
                pass

        elif event == 'END':
            if not self.busy:
                return {'verbose': 'Not listening to HOLD event end here'}

            if time - self.start_time > options.hold_min_threshold:
                if not cancelled:
                    valid, res = self.extend_path(None)
                    if not valid:
                        return self.release(f'No path to action from {res} in {self.path}. Releasing handler')

                    self.available_actions = res[self.wclass] if self.wclass in list(res) else res[None]
                    if 'end' in list(self.available_actions):
                        self.run(command = self.available_actions['end'])

                    self.release()
                else:
                    # This will be hold+gestures
                    # Don't remove handler and set a flag: self.holding = True
                    return self.release()
            else:
                return self.release()

    def begin(self, device_type, gesture, time, fingers):
        'Handle the begin event of all other actions'
        if self.busy and not self.holding:
            return self.release(f'Handler for device {self.device} is busy (shouldn\'t be possible!)')

        self.grab(device_type, time)

        valid, res = self.extend_path(fingers)
        if not valid:
            return self.release(f'No path to action from {res} in {self.path}. Releasing handler')

        # Get gestures that can trigger actions
        self.available_gestures = {k for k, v in res.items() if not {self.wclass, None}.isdisjoint(v['apps'])}

        # Skip if only HOLD gestures registered
        if self.available_gestures == ['HOLD']:
            return self.release(f'No gesture with {fingers} fingers registered for device {self.device}. Releasing handler')

        # Skip if libinput says the gesture is a swipe and there's no swipe action
        if gesture == 'SWIPE':
            if 'swipe' in self.available_gestures:
                self.gesture = 'swipe'
            else:
                return self.release(f'No swipe gesture with {fingers} fingers registered. Releasing handler')

    def update(self, time, fingers, x, y, ratio, angle):
        'Handle the update event of all other actions'
        if not self.busy:
            return {'verbose': 'Not listening to update events for this gesture'}

        # Update handler data
        if ratio:
            ratio = math.log(float(ratio))
            angle = float(angle)
            self.data['dratio'] = ratio - self.data['dratio']
            self.data['ratio'] = ratio
            self.data['dangle'] += angle
            self.data['angle'] += angle

        if x:
            x = float(x)
            y = float(y)
            self.data['x'] += x
            self.data['dx'] += x
            self.data['y'] += y
            self.data['dy'] += y

        x, y, dx, dy, ratio, dratio, angle, dangle = self.data.values()

        # Determine gesture within available gestures
        if not self.gesture:
            self.gesture = 'rotate' if 'rotate' in self.available_gestures and abs(angle) > options.angle_min_threshold \
                     else  'pinch'  if 'pinch'  in self.available_gestures and abs(ratio) > options.ratio_min_threshold \
                     else  'swipe'  if 'swipe'  in self.available_gestures and math.sqrt(x ** 2 + y ** 2) > options.swipe_min_threshold \
                else None

        # Get available motions
        if self.gesture and not self.available_motions:
            _, res = self.extend_path(self.gesture)
            self.available_motions = {k for k, v in res.items() if (not {self.wclass, None}.isdisjoint(list(v)) and k != 'apps')}

        # Determine gesture motion
        if self.available_motions and not self.motion:
            self.motion = 'up'    if 'up' in self.available_motions and abs(y) > abs(x) and y < 0 \
                     else 'down'  if 'down' in self.available_motions and abs(y) > abs(x) and y > 0 \
                     else 'left'  if 'left' in self.available_motions and abs(x) > abs(y) and x < 0 \
                     else 'right' if 'right' in self.available_motions and abs(x) > abs(y) and x > 0 \
                     else 'in'    if 'in' in self.available_motions and ratio < 0 \
                     else 'out'   if 'out' in self.available_motions and ratio > 0 \
                     else 'cw'    if 'cw' in self.available_motions and angle > 0 \
                     else 'ccw'   if 'ccw' in self.available_motions and angle < 0 \
                     else None

        # Register motion only if over *_chain_threshold
        if self.chaining and \
            ((self.gesture == 'swipe' and math.sqrt(x ** 2 + y ** 2) < options.swipe_chain_threshold) or \
             (self.gesture == 'pinch' and abs(ratio) < options.ratio_chain_threshold) or \
             (self.gesture == 'rotate' and abs(angle) < options.angle_chain_threshold)):
            self.motion = None

        # Get available actions
        if self.motion and not self.available_actions:
            _, res = actions.validate_path([*self.path, self.motion])
            self.available_actions = res[self.wclass] if self.wclass in list(res) else res[None]

        # Run early actions (pre, chain, continuous)
        if self.available_actions:
            if self.chaining and 'chain' not in self.available_actions:
                self.motion = None
                self.available_actions = None
                return

            if 'pre' in list(self.available_actions) and not self.pre:
                self.run(command = self.available_actions['pre'])
                self.pre = True

            if 'continuous' in list(self.available_actions) and time - self.start_time > options.update_timer:
                self.run(command = self.available_actions['continuous'])
                self.start_time = time
                self.data['dx'] = 0
                self.data['dy'] = 0
                self.data['dangle'] = 0
                self.data['dratio'] = 0

            if 'chain' in list(self.available_actions):
                self.run(command = self.available_actions['chain'])
                # run for hold+ : gesture is added to path and then motion/wclass/modifier
                self.chaining = True
                self.motion = None
                self.available_actions = None
                self.data = dict(x = 0, y = 0, dx = 0, dy = 0, angle = 0, ratio = 0, dangle = 0, dratio = 0)

    def end(self, cancelled):
        'Handle end event for all actions'
        if not self.busy:
            return self.release(f'Skipping end for device {self.device} as there isn\'t anything to do with it')

        # Run late actions (end, post)
        if self.available_actions:
            if 'end' in list(self.available_actions) and not cancelled:
                self.run(command = self.available_actions['end'])

            if 'post' in list(self.available_actions):
                self.run(command = self.available_actions['post'])

        return self.release()

    def parse(self, event, time, params):
        'Parse a libinput line and dispatch to the relevant listener'
        time = time and float(time)
        event = event.split('_')

        # Skip the event if the device is disabled, not supported, or empty
        if not self.enabled or not params_re.get(event[0]) or not params:
            return

        fields = params_re[event[0]].match(params)

        if not fields:
            if args.debug:
                print(f'Error parsing event {event[0]} params: {params}', file = sys.stderr)
            return

        fields = fields.groupdict()

        if args.raw:
            print(f'Parsed event: {fields}')

        # Dispatch to the relevant listener
        answer = self.LISTENERS[event[0]](event[1:], time, **fields)
        if answer:
            if args.debug and 'debug' in list(answer):
                print(answer['debug'], file = sys.stderr)
            if args.verbose and 'verbose' in list(answer):
                print(answer['verbose'])

    def listener_device(self, event, time, name, seat, group, capabilities, sizex, sizey):
        'Listener for DEVICE lines'
        if event[0] == 'ADDED':
            return self.add(name, capabilities, sizex, sizey)
        elif event[0] == 'REMOVED':
            return self.remove()
        else:
            return {'debug': f'Device event {event} not recognized'}

    def listener_switch(self, event, time, switch, state):
        'Listener for SWITCH lines'
        if event[0] == 'TOGGLE':
            return self.switch(switch, state = 'on' if state == '1' else 'off')
        else:
            return {'debug': f'Device event {event} not recognized'}

    def listener_gesture(self, event, time, fingers, x, y, x2, y2, ratio, angle, cancelled):
        'Listener for GESTURE lines'
        fingers = int(fingers)

        if event[0] == 'HOLD':
            return self.hold('gesture', event[1], time, fingers, cancelled)
        elif event[1] == 'BEGIN':
            return self.begin('gesture', event[0], time, fingers)
        elif event[1] == 'UPDATE':
            return self.update(time, fingers, x, y, ratio, angle)
        elif event[1] == 'END':
            return self.end(cancelled)
        else:
            return {'debug': f'Device event {event} not recognized'}

    def listener_pointer(self, event, time, x, y, button, state, vert, horiz):
        'Listener for POINTER lines'
        if event[0] == 'SCROLL' and event[1] == 'FINGER':
            if not self.busy and not self.holding:
                self.begin('gesture', 'SWIPE', time, 2)

            if self.busy and vert == '0.00' and horiz == '0.00':
                self.end(False)
            else:
                self.update(time, 2, horiz, vert, None, None)

        # BUTTON -> ignore? -> comment regex out so that it is not picked up ?
        # BUTTON : button pressed/released

        # MOTION -> swipe handler 1 / rotate handler 1
        # MOTION : x/y, can't know if begin/update/end
        # x = x and float(x)
        # y = y and float(y)

    # TOUCH_(?P<event> UP | DOWN | FRAME | MOTION)
    def listener_touch(self, event, time, finger, x, y):
        'Listener for TOUCH lines'
        finger = int(finger)
        x = x and float(x)
        y = y and float(y)

        # # Stuff for touch
        # nfingers = 0
        # lastPos = []
        # startPos = []
        # ready = True

    #     if ready:
    #         # Track each new finger and store its starting position
    #         # Build an array of starting position and last know position for each finger, and increment number of fingers
    #         if event == 'DOWN':
    #             lastPos.append((x, y))
    #             startPos = lastPos.copy()
    #             nfingers += 1

    #         # Follow last known position for each finger
    #         if nfingers > 0 and event == 'MOTION':
    #             lastPos[finger] = (x, y)

    #         # Trigger gesture at the first lifted finger
    #         # and stop reading new events until all fingers are up
    #         if nfingers > 0 and event == 'UP':
    #             gesture, params = touch_gesture(startPos, lastPos).values()
    #             handler = handlers.get(gesture)

    #             if handler:
    #                 handler.begin(str(nfingers), time, options.swipe_min_threshold)
    #                 handler.update(params, time)
    #                 handler.end()
    #                 handler = None
    #             else:
    #                 print(f'Unknown gesture received: {gesture}.', file = sys.stderr)

    #             ready = False
    #             nfingers -= 1
    #     else:
    #         # After the gesture is sent, wait for all fingers to be released
    #         nfingers += (event == 'DOWN') - (event == 'UP')

    #         # and reset the logic
    #         if nfingers == 0:
    #             lastPos = []
    #             startPos = []
    #             ready = True

def main():
    # Set up command line arguments
    get_options()

    # Output various info/version info
    if args.verbose:
        xsession = os.getenv('XDG_SESSION_DESKTOP') or os.getenv('DESKTOP_SESSION') or 'unknown'
        xtype = os.getenv('XDG_SESSION_TYPE') or 'unknown'
        print(f'{PROGNAME}: session {xsession}+{xtype} on {platform.platform()}, python {platform.python_version()}')

    # Read and process the conf file
    read_conf(args.conffile, CONFNAME)

    # Listen to libinput debug-events
    cmd = listen_libinput()

    handler = {}

    if args.verbose:
        print('LIBINPUT:')

    # Sit in a loop forever reading the libinput messages.
    for line in cmd.stdout:
        line = line.strip()

        # Parse libinput output
        fields = params_re['LIBINPUT'].match(line)

        # Something very wrong with libinput output has happened
        if not fields:
            sys.exit(f'Error parsing libinput line: {line}')

        device, event, time, params = fields.groupdict().values()

        if args.raw:
            print(f'Raw libinput line: {line}')
            print(f'Parsed libinput line: {device=} {event=} {time=}')

        # Create a handler for every device
        if not handler.get(device):
            handler[device] = HANDLER(device)

        # Pass the event and params to the handler
        handler[device].parse(event, time, params)

        if args.raw:
            print()

if __name__ == '__main__':
    main()
