#!/usr/bin/env python3
'Read gestures from libinput touchpad and action shell commands.'
# Mark Blakeney, Sep 2015
import os
import sys
import argparse
import subprocess
import shlex
import re
import getpass
import fcntl
import platform
import math
import signal
from pathlib import Path
from packaging.version import Version

PROGPATH = Path(sys.argv[0])
PROGNAME = PROGPATH.stem

# Conf file containing gesture commands.
# Search first for user file then system file.
CONFNAME = f'{PROGNAME}.conf'
USERDIR = os.getenv('XDG_CONFIG_HOME', os.path.expanduser('~/.config'))
CONFDIRS = (USERDIR, '/etc')

# Singleton class for storing options
class OPTIONS:
    # Configurable options with their default values and validation functions
    available = dict(
        swipe_min_threshold = dict(default = 5    ,valid = float, help = "Minimum travel distance to register a swipe"),
        ratio_min_threshold = dict(default = .2   ,valid = float, help = "Minimum ratio to register a pinch"),
        angle_min_threshold = dict(default = 10   ,valid = float, help = "Minimum angle to register a rotation"),
        swipe_step_threshold = dict(default = 100 ,valid = float, help = "Minimum travel distance to register a swipe"),
        ratio_step_threshold = dict(default = .4  ,valid = float, help = "Minimum ratio to register a pinch"),
        angle_step_threshold = dict(default = 100 ,valid = float, help = "Minimum angle to register a rotation"),
        update_timer        = dict(default = .1   ,valid = float, help = "Time interval at which update a continuous motion"),
        device              = dict(default = "all",valid = str, help = '"all", or device name, or device path'))

    # Create attributes from the dict and set default values
    def __init__(self):
        for opt, params in self.available.items():
            setattr(self, opt, params["default"])

    def set(self, option, value):
        arg = getattr(args, option)
        valid = self.available[option]["valid"]

        if arg:
            try:
                setattr(self, option, valid(arg))
                return None
            except:
                print(f'Option {option} must be of type {valid.__name__}. Falling back on default')
                return None
        else:
            try:
                setattr(self, option, valid(value))
                return None
            except:
                return f'Option {option} must be of type {valid.__name__}'

    instance = None

    def __new__(cls):
        if cls.instance is None:
            cls.instance = super().__new__(cls)
            return cls.instance

# Create the singleton options object
options = OPTIONS()

args = None

def open_lock(*args):
    'Create a lock based on given list of arguments'
    # We use exclusive assess to a file for this
    fp = Path('/tmp', '-'.join(args) + '.lock').open('w')

    try:
        fcntl.lockf(fp, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except IOError:
        return None

    return fp

def run(cmd, *, check = True, block = False):
    'Run function and return standard output, Popen() handle, or None'
    try:
        if block:
            result = subprocess.check_output(cmd,
                                             universal_newlines = True,
                                             stderr = (None if check else subprocess.DEVNULL))
        else:
            result = subprocess.Popen(cmd)
    except Exception as e:
        result = None
        if check:
            print(str(e), file = sys.stderr)

    return result

def get_libinput_vers():
    'Return the libinput installed version number string'
    # Try to use newer libinput interface then fall back to old (depreciated) interface.
    res = run(('libinput', '--version'), check = False, block = True)

    return res.strip() if res else run(('libinput-list-devices', '--version'), check = False, block = True)

def listen_libinput(device):
    # Make sure only one instance running for current user
    user = getpass.getuser()
    proglock = open_lock(PROGNAME, user)
    if not proglock:
        sys.exit(f'{PROGNAME} is already running for {user}, terminating ..')

    # User needs to belong to the input group to access the device
    # "sudo gpasswd -a $USER input" then log out/in
    devstr = f' --device {device.get("_path")}' if device else ''
    command = f'stdbuf -oL -- libinput debug-events {devstr}'

    cmd = subprocess.Popen(shlex.split(command),
                           stdout = subprocess.PIPE,
                           bufsize = 1,
                           universal_newlines = True)

    # Avoid producing zombie processes
    signal.signal(signal.SIGCHLD, signal.SIG_IGN)

    return cmd

def get_devices_list():
    'Get list of devices and their attributes (as a dict) from libinput'
    stdout = run("libinput", "list-devices")

    if stdout:
        dev = {}

        for line in stdout.splitlines():
            line = line.strip()

            if line and ':' in line:
                key, value = line.split(':', maxsplit = 1)
                dev[key.strip().lower()] = value.strip()
            elif dev:
                yield dev
                dev = {}

        # Ensure we include last device
        if dev:
            yield dev

def get_device_info(name):
    'Determine libinput touchpad device and return device info'
    devices = list(get_devices_list())

    if not devices:
        print('Can not see any devices, did you add yourself to the input group and log out/in?', file = sys.stderr)
        return None

    # If a specific device name was asked for then return that device
    # This is the "Device" name from libinput list-devices command.
    if name:
        kdev = str(Path(name).resolve()) if name[0] == '/' else None

        for d in devices:
            # If the device name starts with a '/' then it is instead
            # considered as the explicit device path although since
            # device paths can change through reboots this is best to be
            # a symlink. E.g. users should use the corresponding full
            # path link under /dev/input/by-path/ or /dev/input/by-id/.
            if kdev:
                if d.get('kernel') == kdev:
                    return d
            elif d.get('device') == name:
                return d

        return None

    # Otherwise look for 1st device with touchpad capabilities
    for d in devices:
        if 'size' in d and 'pointer' in d.get('capabilities'):
            return d

    # Otherwise look for 1st device with touchpad in it's name or, failing that, 1st device with trackpad in it's name
    for txt in ('touch ?pad', 'track ?pad'):
        for d in devices:
            if re.search(txt, d.get('device', ''), re.I):
                return d

    # Give up
    return None

def get_device(name):
    'Determine libinput touchpad device and add fixed path info'
    dev = get_device_info(name)

    if dev:
        devname = dev.get('kernel')
        evname = ''

        if devname:
            devpath = Path(devname)

            # Also determine and prefer a non-volatile path merely because it is more identifying for users.
            for dirstr in ('/dev/input/by-path', '/dev/input/by-id'):
                dirpath = Path(dirstr)

                if dirpath.exists():
                    for path in dirpath.iterdir():
                        if path.resolve() == devpath:
                            devname = str(path)
                            evname = f'({devpath.name})'
                            break
                    if evname:
                        break

        dev['_path'] = devname
        dev['_diag'] = f'{devname}{evname}: {dev.get("device", "?")}'

    return dev

def get_touchpad():
    if not options.device or options.device != "all":
        device = get_device(options.device)

        if not device:
            sys.exit('Could not determine touchpad device.')

    else:
        device = None

    if args.verbose:
        if device:
            print(f'{PROGNAME}: device {device.get("_diag")}')
        else:
            print(f'{PROGNAME}: monitoring all devices')

    return device

def get_options():
    global args
    opt = argparse.ArgumentParser(description = __doc__)
    opt.add_argument('-c',
                     '--conffile',
                     help = 'alternative configuration file')
    opt.add_argument('-v',
                     '--verbose',
                     action = 'store_true',
                     help = 'output diagnostic messages')
    opt.add_argument('-d',
                     '--debug',
                     action = 'store_true',
                     help = 'output diagnostic messages only, do not action gestures')
    for option, params in options.available.items():
        opt.add_argument('--' + option,
                         help = params["help"])
    args = opt.parse_args()

    if args.debug:
        args.verbose = True

def unexpanduser(cfile):
    'Return absolute path name, with $HOME replaced by ~'
    relslash = Path(os.path.abspath(str(cfile)))

    try:
        relhome = relslash.relative_to(os.getenv('HOME'))
    except (ValueError, TypeError):
        relhome = None

    return ('~/' + str(relhome)) if relhome else str(relslash)

# Search for configuration file. Use file given as command line argument,
# else look for file in search dir order.
def read_conf(conffile, defname):
    if conffile:
        confpath = Path(conffile)

        if not confpath.exists():
            sys.exit(f'Conf file "{conffile}" does not exist.')
    else:
        for confdir in CONFDIRS:
            confpath = Path(confdir, defname)

            if confpath.exists():
                break
            else:
                sys.exit('No file {defname} in {" or ".join([unexpanduser(Path(c)) for c in CONFDIRS])}.')

    # Hide any personal user dir/names from diag output
    confname = unexpanduser(confpath)

    # Read and process the conf file
    get_conf(confpath, confname)

    # List out available gestures if that is asked for
    if args.verbose:
        print('', f'Gestures configured in {confname}:', sep = '\n')
        for h in handlers.values():
            for mpair, cmd in h.actions.items():
                action, fingers, *modifiers = mpair
                print(f'{h.name.lower()} {action:15}{fingers:>2} {cmd} {modifiers}')

        print('', 'OPTIONS:', sep = '\n')
        for option, params in options.available.items():
            value = getattr(options, option)
            default = params["default"]
            if value != default:
                print(f'{option:20} {value:>5} ({default=})')
            else:
                print(f'{option:20} {value:>5}')

        print()

conf_comment_re = re.compile(r"""
    ^\# |                                  # Line starts with a comment
    ^\[[^\[\]]+\]\s*                       # Line is a section header
""", flags = re.VERBOSE)

def get_conf(conffile, confname):
    'Read given configuration file and store internal actions etc'
    with conffile.open() as fp:
        for num, line in enumerate(fp, 1):
            line = line.strip()

            if not line or conf_comment_re.match(line):
                continue

            errmsg = get_conf_line(line)

            if errmsg:
                sys.exit(f'Error at line {num} in file {confname}:\n>> {line} <<\n{errmsg}.')

def get_conf_line(line):
    'Process a single line in conf file'
    key, *argslist = line.split(maxsplit = 1)

    if key in list(options.available):
        return options.set(key, argslist[0])
    else:
        conf_func = conf_commands.get(key)

        if not conf_func:
            return f'Configuration command "{key}" is not supported.\nMust be "{" or ".join(conf_commands)}"'

        return conf_func(argslist[0] if argslist else '')

# Table of configuration commands
conf_commands = {}

def add_conf_command(func):
    'Add configuration command to command lookup table based on name'
    conf_commands[re.sub('^conf_', '', func.__name__)] = func

conf_switch_re = re.compile(r"""
    (?P<switch> tablet-mode | lid | keypad-slide) # Switch name
    \s*
    (?P<state> on | off)                          # Toggle state
    \s*
    (?P<command> .*)                              # Command
""", flags = re.VERBOSE)

@add_conf_command
def conf_switch(lineargs):
    'Process a single gesture line in conf file'
    fields = conf_switch_re.match(lineargs)

    # Look for configured gesture. Sanity check the line.
    if not fields:
        return 'Invalid switch line - not enough fields'

    switch, state, command = fields.groupdict().values()
    handler = handlers.get("SWITCH")

    # Add the configured switch
    return handler.add(switch, state, command)

conf_gesture_re = re.compile(r"""
    (?P<gesture> swipe | pinch)                                          # gesture name
    \s*
    (?P<motion> up | down | left | right | in | out | (anti)? clockwise) # gesture motion
    \s*
    (?P<fingers> \d)                                                     # fingers
    \s*
    (?P<modifier> continuous | step | end)?                              # modifier
    \s*
    (?P<command> .*)                                                     # command
""", flags = re.VERBOSE)

@add_conf_command
def conf_gesture(lineargs):
    'Process a single gesture line in conf file'
    fields = conf_gesture_re.match(lineargs)

    # Look for configured gesture. Sanity check the line.
    if not fields:
        return 'Invalid gesture line - not enough fields'

    gesture, motion, fingers, modifier, command = fields.groupdict().values()
    handler = handlers.get(gesture.upper())

    modifier = modifier or 'end'

    if not handler:
        return f'Gesture "{gesture}" is not supported.\nMust be "{" or ".join([h.lower() for h in handlers])}"'

    # Add the configured gesture
    return handler.add(motion.lower(), fingers, modifier, command)

# Table of gesture handlers
handlers = {}

def add_gesture_handler(cls):
    'Create gesture handler instance and add to lookup table based on name'
    handlers[cls.__name__] = cls()

class GESTURE:
    'Abstract base class for handling for gestures'
    def __init__(self):
        'Initialise this gesture at program start'
        self.name = type(self).__name__
        self.actions = {}
        self.has_continuous = False
        self.has_step = False

    def add(self, motion, fingers, modifier, command):
        'Add a configured motion command for this gesture'
        if motion not in self.SUPPORTED_MOTIONS:
            return f'Gesture {self.name.lower()} does not support motion "{motion}".\nMust be "{" or ".join(self.SUPPORTED_MOTIONS)}"'

        if not command:
            return 'No command configured'

        if modifier == "continuous":
            self.has_continuous = True
        elif modifier == "step":
            self.has_step = True

        try:
            self.actions[(motion, fingers, modifier)] = command
        except Exception as e:
            return str(e)

        return None

    def begin(self, fingers, time, threshold):
        'Initialise this gesture at the start of motion'
        self.fingers = fingers
        self.data = dict(x = 0, y = 0, dx = 0, dy = 0, angle = 0, ratio = 0, dangle = 0, dratio = 0)
        self.uptime = time
        self.motion = None
        self.threshold = threshold

    def end(self, cancelled = False):
        'Action this gesture at the end of a motion sequence'

        if cancelled or not self.motion:
            return

        self.action(self.motion, self.fingers, 'end')

    def action(self, motion, fingers, modifier):
        'Action a motion command for this gesture'
        command = self.actions.get((motion, fingers, modifier))

        torun = command

        if torun:
            data = {k: int(v) for k, v in self.data.items()}
            exprs = re.findall(r'\{[^\{\}]+\}', torun)
            for expr in exprs:
                torun = torun.replace(expr, str(eval(expr[1:-1], {}, data)))

        if args.verbose and torun:
            print(f'{PROGNAME}: {self.name} {motion} {fingers} {data}')

            if torun:
                print('  ', torun)
                print('')

        if torun and not args.debug:
            run(shlex.split(torun))

        return True if torun else False

@add_gesture_handler
class SWIPE(GESTURE):
    'Class to handle this type of gesture'
    SUPPORTED_MOTIONS = ('left', 'right', 'up', 'down')

    def update(self, coords, time):
        'Update this gesture for a motion'
        # Ignore this update if we can not parse the numbers we expect
        try:
            x = float(coords[2])
            y = float(coords[3])
        except (ValueError, IndexError):
            return False

        self.data["x"] += x
        self.data["dx"] += x
        self.data["y"] += y
        self.data["dy"] += y

        # Determine swipe direction after swipe_min_threshold has been traveled
        if not self.motion:
            total_dist = math.sqrt(self.data["x"] ** 2 + self.data["y"] ** 2)

            # Require absolute distance movement beyond a small threshold to determine motion
            if total_dist < self.threshold:
                return True

            # Discriminate left/right or up/down.
            if abs(self.data["x"]) > abs(self.data["y"]):
                motion = 'left' if self.data["x"] < 0 else 'right'
            else:
                motion = 'up' if self.data["y"] < 0 else 'down'

            self.motion = motion

        # Trigger action if motion is set and continuous actions are registered
        if self.has_continuous and self.motion and time - self.uptime > options.update_timer:
            self.action(self.motion, self.fingers, "continuous")
            self.uptime = time
            self.data["dx"], self.data["dy"] = 0, 0

        if self.has_step and self.motion and self.action(self.motion, self.fingers, "step"):
            self.begin(self.fingers, time, options.swipe_step_threshold)

        return True

@add_gesture_handler
class PINCH(GESTURE):
    'Class to handle this type of gesture'
    SUPPORTED_MOTIONS = ('in', 'out', 'clockwise', 'anticlockwise')

    def update(self, coords, time):
        'Update this gesture for a motion'
        # Ignore this update if we can not parse the numbers we expect
        try:
            ratio = math.log(float(coords[4]))
            angle = float(coords[5])
        except (ValueError, IndexError):
            return False

        self.data["dratio"] = ratio - self.data["dratio"]
        self.data["dangle"] += angle
        self.data["ratio"] = ratio
        self.data["angle"] += angle

        # Determine rotation/zoom
        if not self.motion:
            if abs(self.data["ratio"]) < options.ratio_min_threshold and abs(self.data["angle"]) < options.angle_min_threshold:
                return True

            if abs(self.data["angle"]) >= options.angle_min_threshold:
                motion = 'clockwise' if self.data["angle"] > 0 else 'anticlockwise'
            else:
                motion = 'in' if self.data["ratio"] < 0 else 'out'

            self.motion = motion

        # Trigger action if motion is set and continuous actions are registered
        if self.has_continuous and self.motion and time - self.uptime > options.update_timer:
            self.action(self.motion, self.fingers, "continuous")
            self.uptime = time
            self.data["dratio"], self.data["dangle"] = 0, 0

        if self.has_step and self.motion and self.action(self.motion, self.fingers, "step"):
            self.begin(self.fingers, time, None)

        return True

@add_gesture_handler
class SWITCH:
    'Class to handle this type of switch'
    SUPPORTED_SWITCHES = ('tablet-mode', 'lid', 'keypad-slide')

    def __init__(self):
        'Initialise this switch at program start'
        self.name = type(self).__name__
        self.actions = {}

    def add(self, switch, state, command):
        'Add a configured motion command for this gesture'
        if switch not in self.SUPPORTED_SWITCHES:
            return f'{self.name.lower()} does not support switch "{switch}".\nMust be "{" or ".join(self.SUPPORTED_MOTIONS)}"'

        if not command:
            return 'No command configured'

        try:
            self.actions[(switch, state)] = command
        except Exception as e:
            return str(e)

        return None

    def action(self, switch, state):
        'Action a motion command for this gesture'
        command = self.actions.get((switch, state))

        if args.verbose:
            print(f'{PROGNAME}: {self.name} {switch} {state}')

            if command:
                print('  ', command)

        if command and not args.debug:
            run(command)

def center(points):
    center = [0, 0]

    for point in points:
        center[0] += point[0]
        center[1] += point[1]

    return (center[0] / len(points), center[1] / len(points))

def diff(point1, point2):
    return((point2[0] - point1[0], point2[1] - point1[1]))

def mean_dist(points, center):
    dist = 0

    for point in points:
        vec = diff(center, point)
        dist += math.sqrt(vec[0]**2 + vec[1]**2)

    return dist / len(points)

def norm_cross_prod(x1, y1, x2, y2):
    return (x1*y2 - x2*y1) / (0.0000001 + math.sqrt(x1**2 + y1**2) * math.sqrt(x2**2 + y2**2))

def calc_angle(startPos, lastPos, startCenter, lastCenter):
    angle = 0
    xc1, yc1 = startCenter
    xc2, yc2 = lastCenter

    for i in range(0, len(startPos)):
        x1, y1 = startPos[i]
        x2, y2 = lastPos[i]
        angle += math.asin(norm_cross_prod(x1 - xc1, y1 - yc1, x2 - xc2, y2 - yc2))

    return angle / len(startPos)

def touch_gesture(startPos, lastPos):
    startCenter = center(startPos)
    lastCenter = center(lastPos)

    xrel, yrel = diff(startCenter, lastCenter)
    dist = math.sqrt(xrel**2 + yrel**2)

    if len(lastPos) > 1:
        ratio = mean_dist(lastPos, lastCenter) / mean_dist(startPos, startCenter)
        angle = calc_angle(startPos, lastPos, startCenter, lastCenter) / math.pi * 180
    else:
        ratio = 1
        angle = 0

    if abs(angle) > options.angle_min_threshold:
        return({'gesture': 'PINCH',
                'params': [0, 0, 0, 0, ratio, angle]})
    elif abs(math.log(ratio)) > options.ratio_min_threshold:
        return({'gesture': 'PINCH',
                'params': [0, 0, 0, 0, ratio, angle]})
    else:
        return({'gesture': 'SWIPE',
                'params': [0, 0, xrel, yrel]})

touch_event_re = re.compile(r"""
    .*?event\d+ \s+ TOUCH_                 # Prefix
    (?P<event> UP | DOWN | FRAME | MOTION) # Event
    \s*
    (?:\d+)?                               # Event number within frame
    \s*
    \+ (?P<time> \d+\.\d+) s               # Time
    \s*
    (?P<params> .*)?                       # Params
""", flags = re.VERBOSE)

touch_params_re = re.compile(r"""
    (?P<finger> \d)                        # Finger
    \s*
    \( (?P=finger) \)
    \s*
    (?P<x> \d+\.\d+) /\s* (?P<y> \d+\.\d+) # Absolute position 0-100% of width/height
""", flags = re.VERBOSE)

switch_event_re = re.compile(r"""
    .*?event\d+ \s+ SWITCH_TOGGLE                            # Prefix
    \s*
    \+ (?P<time> \d+\.\d+) s                                 # Time
    \s*
    switch \s+ (?P<switch> tablet-mode | lid | keypad-slide) # Switch name
    \s*
    state \s+ (?P<state> 0 | 1)                              # State
""", flags = re.VERBOSE)

gesture_event_re = re.compile(r"""
    .*?event\d+ \s+ GESTURE_           # Prefix
    (?P<gesture> SWIPE | PINCH | HOLD) # Gesture
    _
    (?P<event> BEGIN | UPDATE | END)   # Event
    \s*
    (?: \d+)?                          # Update frame number
    \s*
    \+ (?P<time> \d+\.\d+) s           # Time
    \s*
    (?P<fingers> \d)                   # Fingers
    \s*
    (?P<params> .*)?                   # Params
""", flags = re.VERBOSE)

def main():
    # Set up command line arguments
    get_options()

    libvers = get_libinput_vers()

    if args.verbose:
        # Output various info/version info
        xsession = os.getenv('XDG_SESSION_DESKTOP') or os.getenv('DESKTOP_SESSION') or 'unknown'
        xtype = os.getenv('XDG_SESSION_TYPE') or 'unknown'
        print(f'{PROGNAME}: session {xsession}+{xtype} on {platform.platform()}, python {platform.python_version()}, libinput {libvers}')

        # Output hash version/checksum of this program
        vers = run(('md5sum', str(PROGPATH)), check = False, block = True)
        vers = str(vers.split()[0]) if vers else '?'
        print(f'{PROGPATH}: hash {vers}')

    # Read and process the conf file
    read_conf(args.conffile, CONFNAME)

    # Get touchpad device
    device = get_touchpad()

    # Listen to libinput debug-events
    cmd = listen_libinput(device)

    # Sit in a loop forever reading the libinput messages.
    handler = None
    nfingers = 0
    lastPos = []
    startPos = []
    ready = True

    for line in cmd.stdout:
        line = line.strip()

        # Output raw messages if debug
        if args.debug:
            print(line)

        if 'TOUCH_' in line:
            fields = touch_event_re.match(line)

            if not fields:
                print(f'Unknown touch gesture received: {line}.', file = sys.stderr)
                return

            event, time, params = fields.groupdict().values()
            time = float(time)

            if ready:
                # skip FRAME event and return
                if event == 'FRAME':
                    continue

                # skip UP event
                elif event == 'UP':
                    finger, fingerp, pos, realpos, x, y = None, None, None, None, None, None

                # parse params for DOWN and MOTION
                else:
                    fields = touch_params_re.match(params)

                    if not fields:
                        print(f'Unknown touch gesture parameters received: {params}.', file = sys.stderr)
                        return

                    finger, x, y = fields.groupdict().values()

                    finger = int(finger)
                    x = float(x)
                    y = float(y)

                # Track each new finger and store its starting position
                if event == 'DOWN':
                    lastPos.append((x, y))
                    startPos = lastPos.copy()
                    nfingers += 1

                # Follow last known position for each finger
                if nfingers > 0 and event == 'MOTION':
                    lastPos[finger] = (x, y)

                # Trigger gesture at the first lifted finger
                if nfingers > 0 and event == 'UP':
                    gesture, params = touch_gesture(startPos, lastPos).values()
                    handler = handlers.get(gesture)

                    if handler:
                        handler.begin(str(nfingers), time, options.swipe_min_threshold)
                        handler.update(params, time)
                        handler.end()
                        handler = None
                    else:
                        print(f'Unknown gesture received: {gesture}.', file = sys.stderr)

                    ready = False
                    nfingers -= 1
            else:
                # After the gesture is sent, wait for all fingers to be released
                nfingers += (event == 'DOWN') - (event == 'UP')

                if nfingers == 0:
                    lastPos = []
                    startPos = []
                    ready = True
                continue

        if "SWITCH_" in line:
            fields = switch_event_re.match(line)

            if not fields:
                print(f'Unknown switch toggle received: {line}.', file = sys.stderr)
                return

            handler = handlers.get("SWITCH")

            time, switch, state = fields.groupdict().values()

            handler.action(switch, "on" if state == '1' else "off")
            handler = None

        if 'GESTURE_' in line:
            # Split received message line into relevant fields
            fields = gesture_event_re.match(line)

            if not fields:
                print(f'Unknown gesture + event received: {line}.', file = sys.stderr)
                return

            gesture, event, time, fingers, params = fields.groupdict().values()
            time = float(time)

            # Action each type of event
            if event == 'BEGIN':
                handler = handlers.get(gesture)

                if handler:
                    handler.begin(fingers, time, options.swipe_min_threshold)
                else:
                    print(f'Unknown gesture received: {gesture}.', file = sys.stderr)

            elif event == 'UPDATE':
                if handler:
                    if not handler.update(re.split(r'[^-.\d]+', params), time):
                        print(f'Could not parse {gesture} {event}: {params}', file = sys.stderr)

            elif event == 'END':
                if handler:
                    handler.end(params == "cancelled")
                    handler = None

if __name__ == '__main__':
    main()
