#!/usr/bin/env python3
'Execute shell commands and emulate inputs based on libinput events'
# Maxime Wack 2026

import os
import sys
import argparse
import subprocess
import shlex
import re
import getpass
import fcntl
import platform
import math
import signal
from time import monotonic
from pathlib import Path

PROGNAME = Path(sys.argv[0]).stem

# Conf file containing gesture commands.
# Search first for user file then system file.
CONFNAME = f'{PROGNAME}.conf'
CONFDIRS = (os.getenv('XDG_CONFIG_HOME', os.path.expanduser('~/.config')), '/etc')

conf_prefix = []
wclass_prefix = None
cmd = None
conf_lastmodif = None

class OPTIONS:
    'Singleton class for storing options'

    # Configurable options with their default values and validation functions
    available = dict(
        swipe_min_threshold   = dict(default = 5    , valid = float, help = 'Minimum travel distance to register a swipe'),
        ratio_min_threshold   = dict(default = .2   , valid = float, help = 'Minimum ratio to register a pinch'),
        angle_min_threshold   = dict(default = 10   , valid = float, help = 'Minimum angle to register a rotation'),
        hold_min_threshold    = dict(default = .5   , valid = float, help = 'Minimum time (in s) to register a hold'),
        swipe_chain_threshold = dict(default = 100  , valid = float, help = 'Minimum travel distance to register a chained swipe'),
        ratio_chain_threshold = dict(default = .4   , valid = float, help = 'Minimum ratio to register a chained pinch'),
        angle_chain_threshold = dict(default = 100  , valid = float, help = 'Minimum angle to register a chained rotation'),
        update_timer          = dict(default = .1   , valid = float, help = 'Time interval at which update a continuous motion'))

    def __init__(self):
        'Create attributes from the dict and set default values'
        for opt, params in self.available.items():
            setattr(self, opt, params['default'])

    def set(self, option, value):
        'Set an option value (arg > conf > default)'
        arg = getattr(args, option)
        valid = self.available[option]['valid']

        if arg:
            try:
                setattr(self, option, valid(arg))
            except:
                return f'Option {option} must be of type {valid.__name__}. Falling back on default'
        else:
            try:
                setattr(self, option, valid(value))
            except:
                return f'Option {option} must be of type {valid.__name__}'

    instance = None

    def __new__(self):
        'Ensure single instance'
        if self.instance is None:
            self.instance = super().__new__(self)

        return self.instance

# Create the singleton options object
options = OPTIONS()

class ACTIONS:
    'Singleton class for storing actions'

    # Configurable actions and how to parse them
    available = dict(switch = {'toggle'   : ('tablet-mode', 'lid', 'keypad-slide'),
                               'state'    : ('on', 'off'),
                               'command'  : '.*'},
                     swipe =  {'fingers' : r'\d',
                               'motion'   : ('up', 'down', 'left', 'right'),
                               'modifier?': ('pre', 'chain', 'continuous', 'end', 'post'),
                               'command'  : r'[^\[\]]+',
                               'wclass?'   : r'\[.*\]'},
                     pinch =  {'fingers' : r'\d',
                               'motion'   : ('in', 'out'),
                               'modifier?': ('pre', 'chain', 'continuous', 'end', 'post'),
                               'command'  : r'[^\[\]]+',
                               'wclass?'   : r'\[.*\]'},
                     rotate = {'fingers' : r'\d',
                               'motion'   : ('cw', 'ccw'),
                               'modifier?': ('pre', 'chain', 'continuous', 'end', 'post'),
                               'command'  : r'[^\[\]]+',
                               'wclass?'   : r'\[.*\]'},
                     hold =   {'fingers' : r'\d',
                               'modifier?': ('pre', 'continuous', 'end'),
                               'command'  : r'[^\[\]]+',
                               'wclass?'   : r'\[.*\]'})

    conf_re = {}
    actions = {}
    parsed_actions = []

    def __init__(self):
        'Build parsing regexes from dict'
        for action, params in self.available.items():
            verbs = []
            for verb, arg in params.items():
                arg = '|'.join(arg) if type(arg).__name__ != 'str' else arg
                if verb[-1] == '?':
                    verbs.append(rf"""(?P<{verb[:-1]}>{arg})?""")
                else:
                    verbs.append(rf"""(?P<{verb}>{arg})""")
            self.conf_re[action] = re.compile(rf"""\s*""".join(verbs))

    def parse(self, restrict, hold, action, args):
        'Parse a conf line with the action regexes'
        fields = self.conf_re[action].match(args)

        if not fields:
            return f'Could not parse {action} line'

        fields = fields.groupdict()

        if action == 'switch':
            self.add_switch(**fields)
        else:
            self.add(restrict, hold, action, **fields)

    def add_switch(self, toggle, state, command):
        'Add a switch action'
        self.parsed_actions.append(f'switch {toggle:12} {state:3} {command}')
        self.build_path('switch', toggle, state, command = command)

    def add(self, restrict, hold, action, fingers, wclass, modifier, command, motion = 'still'):
        'Add all other actions'
        fingers = int(fingers)
        modifier = modifier or 'end'

        wclass = wclass and wclass[1:-1] or wclass_prefix

        self.parsed_actions.append(f'{restrict or '':7} {hold or ''}{action:6} {fingers} {motion or '':5} {modifier:10} {command:60} {wclass or '':>}')

        restrict = [restrict] if restrict else ['touch', 'gesture']

        for r in restrict:
            if hold:
                self.build_path(r, fingers, 'hold', action, motion, wclass, modifier, command = command)
                if not self.actions[r][fingers]['hold'][action].get('apps'):
                    self.actions[r][fingers]['hold'][action]['apps'] = set()

                self.actions[r][fingers]['hold'][action]['apps'].add(wclass)
                action = 'hold'
            else:
                self.build_path(r, fingers, action, motion, wclass, modifier, command = command)

            if not self.actions[r][fingers][action].get('apps'):
                self.actions[r][fingers][action]['apps'] = set()

            self.actions[r][fingers][action]['apps'].add(wclass)

    def build_path(self, *args, command):
        'Construct the actions dict object up to the given path'
        current = self.actions

        for arg in args[:-1]:
            if not current.get(arg):
                current[arg] = {}
            current = current[arg]

        current[args[-1]] = command

    def __str__(self):
        return '\n'.join(sorted(self.parsed_actions))

    instance = None

    def __new__(self):
        'Ensure single instance'
        if self.instance is None:
            self.instance = super().__new__(self)
        # Reset if re-creating
        else:
            self.conf_re = {}
            self.actions = {}
            self.parsed_actions = []

        return self.instance

actions = ACTIONS()

args = None

def open_lock(*args):
    'Create a lock based on given list of arguments'
    # We use exclusive assess to a file for this
    fp = Path('/tmp', '-'.join(args) + '.lock').open('a')

    # Acquire lock
    try:
        fcntl.lockf(fp, fcntl.LOCK_EX | fcntl.LOCK_NB)
    # If lock exists, send SIGUSR1 to running process to reload conf and exit
    except IOError:
        fpid = Path('/tmp', '-'.join(args) + '.lock').open('r')
        running_pid = int(fpid.readline())
        os.kill(running_pid, signal.SIGUSR1)
        fpid.close()
        return None

    fp.close()

    # Write pid into lockfile
    fp = Path('/tmp', '-'.join(args) + '.lock').open('w')
    fcntl.lockf(fp, fcntl.LOCK_EX | fcntl.LOCK_NB)
    fp.write(str(os.getpid()))
    fp.flush()

    return fp

def listen_libinput():
    'Run libinput debug-events and listen to its output'
    # User needs to belong to the input group to access the device ('sudo gpasswd -a $USER input') then log out/in
    return subprocess.Popen(shlex.split(f'stdbuf -oL -- libinput debug-events'),
                           stdout = subprocess.PIPE,
                           bufsize = 1,
                           universal_newlines = True)

def get_options():
    'Parse the command-line options'
    global args
    opt = argparse.ArgumentParser(description = __doc__)
    opt.add_argument('-c',
                     '--conffile',
                     help = 'alternative configuration file')
    opt.add_argument('-v',
                     '--verbose',
                     action = 'store_true',
                     help = 'output diagnostic messages')
    opt.add_argument('-d',
                     '--debug',
                     action = 'store_true',
                     help = 'output diagnostic messages only, do not action gestures')
    opt.add_argument('-r',
                     '--raw',
                     action = 'store_true',
                     help = 'output raw libinput output')
    for option, params in options.available.items():
        opt.add_argument('--' + option,
                         help = params['help'])
    args = opt.parse_args()

    if args.debug:
        args.verbose = True

def unexpanduser(cfile):
    'Return absolute path name, with $HOME replaced by ~'
    relslash = Path(os.path.abspath(str(cfile)))

    try:
        relhome = relslash.relative_to(os.getenv('HOME'))
    except (ValueError, TypeError):
        relhome = None

    return ('~/' + str(relhome)) if relhome else str(relslash)

def read_conf(conffile, defname):
    'Search for configuration file. Use file given as command line argument, else look for file in search dir order'
    global conf_lastmodif

    if conffile:
        confpath = Path(conffile)

        if not confpath.exists():
            sys.exit(f'\033[91mConf file {conffile} does not exist.\033[0m')
    else:
        for confdir in CONFDIRS:
            confpath = Path(confdir, defname)

            if confpath.exists():
                args.conffile = confpath
                break
            else:
                sys.exit('\033[91mNo file {defname} in {" or ".join([unexpanduser(Path(c)) for c in CONFDIRS])}.\033[0m')

    conf_lastmodif = os.stat(confpath).st_mtime

    # Hide any personal user dir/names from diag output
    confname = unexpanduser(confpath)

    # Read and process the conf file
    get_conf(confpath, confname)

    # List out configured options and actions
    verbose('\nOPTIONS:')
    for option, params in options.available.items():
        value = getattr(options, option)
        default = params['default']
        if value != default:
            verbose(f'{option:24} {value:>5} ({default=})')
        else:
            verbose(f'{option:24} {value:>5}')

    verbose('\nACTIONS:')
    verbose(actions)

def get_conf(conffile, confname):
    'Read given configuration file and store internal actions etc'
    global wclass_prefix

    with conffile.open() as fp:
        for num, line in enumerate(fp, 1):
            line = line.expandtabs(2).rstrip()

            # comments
            line = re.sub(r'\s*#.*$', '', line)
            if not line.strip():
                continue

            if re.match(r'^\[.*\]$', line.strip()):
                wclass_prefix = line.strip()[1:-1]
                continue

            errmsg = get_conf_line(line)

            if errmsg:
                sys.exit(f'\033[91mError at line {num} in file {confname}:\n>> {line} <<\n{errmsg}.\033[0m')

def get_conf_line(line):
    'Process a single line in conf file'
    global conf_prefix

    # conf prefix
    # Get current line indentation
    indent = (len(line) - len(line.lstrip(' '))) // 2

    if indent > len(conf_prefix):
        return f'Wrong indentation'

    # Use the prefix up to the indentation level
    conf_prefix = conf_prefix[:indent]

    # Add words to the prefix
    if line[-1] == ':':
        conf_prefix.append(line[:-1])
        return None

    key, argslist = (' '.join(conf_prefix) + ' ' + line).split(maxsplit = 1)

    restrict = None
    hold = None

    if key == 'touch' or key == 'gesture':
        restrict = key
        key, argslist = argslist.split(maxsplit = 1)

    if key[:5] == 'hold+':
        hold = 'hold+'
        key = key[5:]

    if key in options.available:
        return options.set(key, argslist)
    elif key in actions.available:
        return actions.parse(restrict, hold, key, argslist)
    else:
        return f'Unavailable action/option {key}'

def reload(signum = None, frame = None):
    global actions, handlers, cmd, conf_prefix, wclass_prefix

    verbose('Reloading…')

    # Reset handlers and read_conf prefixes
    handlers = {}
    conf_prefix = []
    wclass_prefix = None

    # Reset actions and re-read from conf
    actions = ACTIONS()
    read_conf(args.conffile, CONFNAME)

    # Reset libinput
    cmd.terminate()
    cmd = listen_libinput()

def verbose(message):
    if args.verbose:
        print(message)

def debug(message):
    if args.debug:
        print(f'\033[93m{message}\033[0m', file = sys.stderr)

class HANDLER:
    'Class for device handler objects'

    # Available capabilities
    cap_dict = dict(k = 'keyboard',
                    T = 'tablet',
                    t = 'touch', # in actions
                    p = 'pointer', # match to gesture too ? or disregard because we don't want simple pointers ?
                    g = 'gesture', # in actions
                    S = 'switch') # in actions

    # Parsing regexes for libinput events
    params_re = dict(
        LIBINPUT = re.compile(r""".*? (?P<device> event\d+)                  # Device
                                  \s* (?P<event> [A-Z_]+)                    # Event
                                  \s* (?:\d+)?                               # Event number within frame
                                  \s* (\+ (?: \d+\.\d+) s)?                  # Time
                                  \s* (?P<params> .*)?                       # Params""", flags = re.VERBOSE),

        DEVICE = re.compile(r"""(?P<name>.*?)                                # Device name
                                \s* (?P<seat>seat\d \s default)              # Seat
                                \s* (?P<group>group\d+)                      # Group
                                \s* (cap:(?P<capabilities>[kpgStT]+))        # Capabilities
                                \s* (size \s (?P<sizex>\d+) x (?P<sizey>\d+) mm)? """, flags = re.VERBOSE),

        SWITCH = re.compile(r"""switch
                                \s+ (?P<switch> tablet-mode | lid | keypad-slide) # Switch name
                                \s* state \s+ (?P<state> 0 | 1)                   # State """, flags = re.VERBOSE),

        TOUCH = re.compile(r"""(?P<finger> \d)?                              # Finger
                            \s* \( (?P=finger) \)?
                            \s* ((?P<x> \d+\.\d+) /\s* (?P<y> \d+\.\d+))? # Absolute position 0-100% of width/height """, flags = re.VERBOSE),

        GESTURE = re.compile(r"""(?P<fingers> \d)                                                  # Fingers
                                \s* (?P<cancelled>cancelled)?
                                \s* ((?P<x> -? \d+\.\d+) \s* / \s* (?P<y> -? \d+\.\d+))?                                # Absolute position 0-100% of width/height
                                \s* ( \( \s* (?P<x2> -? \d+\.\d+) \s* / \s* (?P<y2> -? \d+\.\d+) \s* unaccelerated\) )? # Absolute position 0-100% of width/height
                                \s* ((?P<ratio> \d+\.\d+) \s* @ \s* (?P<angle> -? \d+\.\d+))? """, flags = re.VERBOSE),

        POINTER = re.compile(r"""((?P<x> -? \d+\.\d+) \s* / \s* (?P<y> -? \d+\.\d+))?
                                (BTN_(?P<button> LEFT | MIDDLE | RIGHT) \s \( \d+ \) \s (?P<state> pressed | released))?
                                (vert \s ((?P<vert> -?\d+\.\d+) / 0\.0 \*?) \s horiz \s ((?P<horiz> -?\d+\.\d+) / 0\.0 \*?))? """, flags = re.VERBOSE))

    def __init__(self, device):
        'Initialize a device handler'
        self.device = device
        self.LISTENERS = dict(DEVICE  = self.listener_device,
                              TOUCH   = self.listener_touch,
                              GESTURE = self.listener_gesture,
                              SWITCH  = self.listener_switch,
                              POINTER = self.listener_pointer)
        self.state = set()

    def add(self, name, capabilities, sizex, sizey):
        'Populate handler parameters and disable if none of its capabilities is used in configured actions'
        self.name = name
        self.capabilities = {v for k, v in self.cap_dict.items() if k in capabilities}
        self.size = (sizex, sizey)

        self.state = {'disabled'} if self.capabilities.isdisjoint(actions.actions) else set()
        verbose(f'{'Ignoring' if 'disabled' in self.state else 'Adding   '} device {name:50} ({self.device}) {self.capabilities}')

    def remove(self):
        'Remove the handler for an unplugged device'
        del(handlers[self.device])
        verbose(f'Removing device  {self.name:50} ({self.device})')

    def grab(self, *items):
        'Grab a handler and reset it, set the focused window class, and filter the reachable actions'
        self.reset()
        self.actions = {k:v for k, v in actions.actions.items() if k in self.capabilities}
        self.available_actions = []

        self.state = {'busy'}
        self.wclass = subprocess.run(['xdotool', 'getwindowfocus', 'getwindowclassname'], capture_output = True).stdout.decode('utf-8').strip()

        for item in items:
           self.actions = self.actions.get(item)
           if not self.actions:
               return False

        return True

    def release(self, message = None):
        'Release a handler'
        self.state = set()
        if message:
            verbose(message)

    def reset(self):
        'Reset a handler gesture progression'
        self.data = dict(x = 0, y = 0, dx = 0, dy = 0, ratio = 0, dratio = 0, angle = 0, dangle = 0)
        self.start_time = monotonic()
        self.available_gestures = []
        self.available_motions = []
        self.gesture = None
        self.motion = None

    def run(self, command):
        'Run the given command with replacement of {}'
        data = {k: int(v) for k, v in self.data.items()}
        exprs = re.findall(r'\{[^\{\}]+\}', command)
        for expr in exprs:
            command = command.replace(expr, str(eval(expr[1:-1], {}, data)))

        verbose(f'\033[1m\033[92m  {command}\033[0m')

        if not args.debug:
            subprocess.run(shlex.split(command))

    def switch(self, switch, state):
        'Handle a switch action'
        if self.state:
            return debug(f'Handler for device {self.device} is in use (shouldn\'t be possible!)')

        if self.grab('switch', switch, state):
            self.run(self.actions)

        self.release()

    def begin(self, device_type, time, fingers):
        'Handle begin event'
        # Only grab handler if not in a hold+ gesture
        if not 'holding' in self.state:
            if self.state:
                return debug(f'Handler for device {self.device} is busy (shouldn\'t be possible!)')

            if not self.grab(device_type, fingers):
                return self.release(f'No gesture action with {fingers} fingers. Releasing handler')

    def update(self, time, fingers, x, y, ratio, angle):
        'Handle update event'
        if not self.state:
            return verbose('Not listening to update events for this gesture')

        # Update handler data
        if ratio:
            ratio = math.log(float(ratio))
            angle = float(angle)
            self.data['dratio'] = ratio - self.data['dratio']
            self.data['ratio'] = ratio
            self.data['dangle'] += angle
            self.data['angle'] += angle

        if x:
            x = float(x)
            y = float(y)
            self.data['x'] += x
            self.data['dx'] += x
            self.data['y'] += y
            self.data['dy'] += y

        x, y, dx, dy, ratio, dratio, angle, dangle = self.data.values()

        # Get available gestures
        if not self.available_gestures:
            self.available_gestures = {k for k, v in self.actions.items() if k != 'apps' and not {self.wclass, None}.isdisjoint(v.get('apps') or set())}

        # Determine gesture
        if not self.gesture:
            self.gesture = 'rotate' if 'rotate' in self.available_gestures and abs(angle) > options.angle_min_threshold \
                     else  'pinch'  if 'pinch'  in self.available_gestures and abs(ratio) > options.ratio_min_threshold \
                     else  'swipe'  if 'swipe'  in self.available_gestures and math.sqrt(x ** 2 + y ** 2) > options.swipe_min_threshold \
                     else  'hold'   if 'hold'   in self.available_gestures and time - self.start_time > options.hold_min_threshold \
                else None

        # Get available motions
        if self.gesture and not self.available_motions:
            res = self.actions[self.gesture]
            self.available_motions = {k for k, v in res.items() if (not {self.wclass, None}.isdisjoint(list(v)) and k != 'apps')}

        # Determine motion
        if self.available_motions and not self.motion:
            self.motion = 'up'    if 'up'    in self.available_motions and abs(y) > abs(x) and y < 0 \
                     else 'down'  if 'down'  in self.available_motions and abs(y) > abs(x) and y > 0 \
                     else 'left'  if 'left'  in self.available_motions and abs(x) > abs(y) and x < 0 \
                     else 'right' if 'right' in self.available_motions and abs(x) > abs(y) and x > 0 \
                     else 'in'    if 'in'    in self.available_motions and ratio < 0 \
                     else 'out'   if 'out'   in self.available_motions and ratio > 0 \
                     else 'cw'    if 'cw'    in self.available_motions and angle > 0 \
                     else 'ccw'   if 'ccw'   in self.available_motions and angle < 0 \
                     else 'still' if 'still' in self.available_motions \
                     else None

        # Register motion only if over *_chain_threshold
        if 'chain' in self.state and \
            ((self.gesture == 'swipe'  and math.sqrt(x ** 2 + y ** 2) < options.swipe_chain_threshold) or \
             (self.gesture == 'pinch'  and abs(ratio) < options.ratio_chain_threshold) or \
             (self.gesture == 'rotate' and abs(angle) < options.angle_chain_threshold)):
            self.motion = None

        # Get available actions
        if self.motion:
            res = self.actions[self.gesture][self.motion]
            self.available_actions = res[self.wclass] if self.wclass in res else res[None]

        # Run early actions (pre, chain, continuous)
        if self.available_actions:
            # Reset motion if only end action to mimic legacy behavior
            if list(self.available_actions) == ['end']:
                self.motion = None

            # Discard non chaining motions when chaining
            if 'chain' in self.state and 'chain' not in self.available_actions:
                self.motion = None
                self.available_actions = []
                return

            # Execute pre action only once
            if 'pre' in self.available_actions and not 'pre' in self.state:
                self.run(self.available_actions['pre'])
                self.state.add('pre')

            # Execute continuous action every timer tick and reset time and delta data
            if 'continuous' in self.available_actions and time - self.start_time > options.update_timer:
                self.run(self.available_actions['continuous'])
                self.start_time = time
                self.data['dx'] = 0
                self.data['dy'] = 0
                self.data['dangle'] = 0
                self.data['dratio'] = 0

            # Execute chain action and reset prior to determining motion
            if 'chain' in self.available_actions and self.motion:
                self.run(self.available_actions['chain'])
                self.state.add('chain')
                self.motion = None
                self.data = dict(x = 0, y = 0, dx = 0, dy = 0, angle = 0, ratio = 0, dangle = 0, dratio = 0)

        # Set holding if holding still
        if not 'holding' in self.state and self.motion == 'still':
            self.state.add('holding')
            self.actions = self.actions['hold']
            self.reset()

    def end(self, cancelled):
        'Handle end event'
        if not self.state:
            return verbose(f'Skipping end for device {self.device} as there isn\'t anything to do with it')

        if 'holding' in self.state:
            if cancelled:
                if not self.gesture and list(self.actions) != ['still', 'apps']:
                    return
                elif self.gesture and list(self.actions) != ['still', 'apps']:
                    pass
                else:
                    return self.release(f'No hold+ action. Releasing handler')# if list(self.actions) == ['still', 'apps'] else None
        else:
            if not self.gesture:
                return self.release(f'Hold too short') if 'hold' in self.available_gestures else self.release()

        # Run late actions (end, post)
        if self.available_actions:
            if 'end' in self.available_actions and not cancelled:
                self.run(self.available_actions['end'])

            if 'post' in self.available_actions:
                self.run(self.available_actions['post'])

        self.release()

    def parse(self, event, params):
        'Parse a libinput line and dispatch to the relevant listener'
        event = event.split('_')

        # Skip the event if the device is disabled, not supported, or empty
        if 'disabled' in self.state or not self.params_re.get(event[0]) or not params:
            return

        fields = self.params_re[event[0]].match(params)

        if not fields:
            debug(f'Error parsing event {event[0]} params: {params}', file = sys.stderr)
            return

        fields = fields.groupdict()

        if args.raw:
            print(f'Parsed event: {fields}')

        # Dispatch to the relevant listener
        answer = self.LISTENERS[event[0]](event[1:], monotonic(), **fields)

    def listener_device(self, event, time, name, seat, group, capabilities, sizex, sizey):
        'Listener for DEVICE lines'
        if event[0] == 'ADDED':
            self.add(name, capabilities, sizex, sizey)
        elif event[0] == 'REMOVED':
            self.remove()
        else:
            debug(f'Device event {event} not recognized')

    def listener_switch(self, event, time, switch, state):
        'Listener for SWITCH lines'
        if event[0] == 'TOGGLE':
            self.switch(switch, state = 'on' if state == '1' else 'off')
        else:
            debug(f'Device event {event} not recognized')

    def listener_gesture(self, event, time, fingers, x, y, x2, y2, ratio, angle, cancelled):
        'Listener for GESTURE lines'
        fingers = int(fingers)

        if event[1] == 'BEGIN':
            self.begin('gesture', time, fingers)
        elif event[1] == 'UPDATE':
            self.update(time, fingers, x, y, ratio, angle)
        elif event[1] == 'END':
            self.end(cancelled)
        else:
            debug(f'Device event {event} not recognized')

    def listener_pointer(self, event, time, x, y, button, state, vert, horiz):
        'Listener for POINTER lines'
        if event[0] == 'SCROLL' and event[1] == 'FINGER':
            if not self.state:
                self.begin('gesture', time, 2)

            if self.state and vert == '0.00' and horiz == '0.00':
                self.end(False)
            else:
                self.update(time, 2, horiz, vert, None, None)

        # BUTTON -> ignore? -> comment regex out so that it is not picked up ?
        # BUTTON : button pressed/released

        # MOTION -> swipe handler 1 / rotate handler 1
        # MOTION : x/y, can't know if begin/update/end
        # x = x and float(x)
        # y = y and float(y)

    # TOUCH_(?P<event> UP | DOWN | FRAME | MOTION)
    def listener_touch(self, event, time, finger, x, y):
        'Listener for TOUCH lines'
        finger = int(finger)
        x = x and float(x)
        y = y and float(y)

        def center(points):
            center = [0, 0]

            for point in points:
                center[0] += point[0]
                center[1] += point[1]

            return (center[0] / len(points), center[1] / len(points))

        def diff(point1, point2):
            return((point2[0] - point1[0], point2[1] - point1[1]))

        def mean_dist(points, center):
            dist = 0

            for point in points:
                vec = diff(center, point)
                dist += math.sqrt(vec[0]**2 + vec[1]**2)

            return dist / len(points)

        def norm_cross_prod(x1, y1, x2, y2):
            return (x1*y2 - x2*y1) / (0.0000001 + math.sqrt(x1**2 + y1**2) * math.sqrt(x2**2 + y2**2))

        def calc_angle(startPos, lastPos, startCenter, lastCenter):
            angle = 0
            xc1, yc1 = startCenter
            xc2, yc2 = lastCenter

            for i in range(0, len(startPos)):
                x1, y1 = startPos[i]
                x2, y2 = lastPos[i]
                angle += math.asin(norm_cross_prod(x1 - xc1, y1 - yc1, x2 - xc2, y2 - yc2))

            return angle / len(startPos)

        def touch_gesture(startPos, lastPos):
            startCenter = center(startPos)
            lastCenter = center(lastPos)

            xrel, yrel = diff(startCenter, lastCenter)
            dist = math.sqrt(xrel**2 + yrel**2)

            if len(lastPos) > 1:
                ratio = mean_dist(lastPos, lastCenter) / mean_dist(startPos, startCenter)
                angle = calc_angle(startPos, lastPos, startCenter, lastCenter) / math.pi * 180
            else:
                ratio = 1
                angle = 0

            if abs(angle) > options.angle_min_threshold:
                return({'gesture': 'PINCH',
                        'params': [0, 0, 0, 0, ratio, angle]})
            elif abs(math.log(ratio)) > options.ratio_min_threshold:
                return({'gesture': 'PINCH',
                        'params': [0, 0, 0, 0, ratio, angle]})
            else:
                return({'gesture': 'SWIPE',
                        'params': [0, 0, xrel, yrel]})

        # motion > .5mm : go from hold to gesture
        # quick hold? timeout : 40ms
        # hold timeout : 180ms

        # Should be able so send:
        # self.begin('touch', time, fingers)
        # self.update(time, fingers, x, y, ratio, angle)
        # self.end(cancelled)

        # # Stuff for touch
        # nfingers = 0
        # lastPos = []
        # startPos = []
        # ready = True

    #     if ready:
    #         # Track each new finger and store its starting position
    #         # Build an array of starting position and last know position for each finger, and increment number of fingers
    #         if event == 'DOWN':
    #             lastPos.append((x, y))
    #             startPos = lastPos.copy()
    #             nfingers += 1

    #         # Follow last known position for each finger
    #         if nfingers > 0 and event == 'MOTION':
    #             lastPos[finger] = (x, y)

    #         # Trigger gesture at the first lifted finger
    #         # and stop reading new events until all fingers are up
    #         if nfingers > 0 and event == 'UP':
    #             gesture, params = touch_gesture(startPos, lastPos).values()
    #             handler = handlers.get(gesture)

    #             if handler:
    #                 handler.begin(str(nfingers), time, options.swipe_min_threshold)
    #                 handler.update(params, time)
    #                 handler.end()
    #                 handler = None
    #             else:
    #                 print(f'Unknown gesture received: {gesture}.', file = sys.stderr)

    #             ready = False
    #             nfingers -= 1
    #     else:
    #         # After the gesture is sent, wait for all fingers to be released
    #         nfingers += (event == 'DOWN') - (event == 'UP')

    #         # and reset the logic
    #         if nfingers == 0:
    #             lastPos = []
    #             startPos = []
    #             ready = True

def main():
    global cmd, handlers

    # Make sure only one instance running for current user
    user = getpass.getuser()
    proglock = open_lock(PROGNAME, user)
    if not proglock:
        sys.exit(f'\033[91m{PROGNAME} is already running for {user}, reloading conf\033[0m')

    # Restart when receiving SIGUSR1
    signal.signal(signal.SIGUSR1, reload)

    # Set up command line arguments
    get_options()

    # Output various info/version info
    xsession = os.getenv('XDG_SESSION_DESKTOP') or os.getenv('DESKTOP_SESSION') or 'unknown'
    xtype = os.getenv('XDG_SESSION_TYPE') or 'unknown'
    verbose(f'{PROGNAME}: session {xsession}+{xtype} on {platform.platform()}, python {platform.python_version()}')

    # Read and process the conf file
    read_conf(args.conffile, CONFNAME)

    # Listen to libinput debug-events
    cmd = listen_libinput()

    handlers = {}

    verbose('\nLIBINPUT:')

    # Ensure stdout it blocking at startup
    os.set_blocking(cmd.stdout.fileno(), True)

    # Sit in a loop forever reading the libinput messages.
    while True:
        line = cmd.stdout.readline().strip()

        # Parse libinput output
        if line:
            fields = HANDLER.params_re['LIBINPUT'].match(line)

            # Something very wrong with libinput output has happened
            if not fields:
                sys.exit(f'\033[91mError parsing libinput line: {line}\033[0m')

            device, event, params = fields.groupdict().values()

            if args.raw:
                print(f'\033[95m{line}\033[0m')
                print(f'Parsed libinput line: {device=} {event=}')

            # Create a handler for every device
            if not handlers.get(device):
                handlers[device] = HANDLER(device)

            # Pass the event and params to the handler
            handlers[device].parse(event, params)

            if args.raw:
                print()

            # Break for holding handlers
            for _, handler in handlers.items():
                if 'busy' in handler.state:
                    os.set_blocking(cmd.stdout.fileno(), False)
        else:
            # Update on a timer (mainly to allow hold to happen)
            anyholding = False
            for _, handler in handlers.items():
                if 'busy' in handler.state:
                    anyholding = True
                    handler.update(monotonic(), None, None, None, None, None)

            if not anyholding:
                os.set_blocking(cmd.stdout.fileno(), True)

        # Reload conf if conf file changes
        if os.stat(args.conffile).st_mtime != conf_lastmodif:
            reload()

if __name__ == '__main__':
    main()
